name: Build & Deploy

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Run Yarn Install & Build
        working-directory: ./web
        run: |
          yarn install
          yarn run build
      
      - name: Deploy to GitHub branch
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: website # The branch the action should deploy to.
          FOLDER: 'web/dist' # The folder the action should deploy.
          
      - name: Deploy to Coding.net branch
        working-directory: web/dist
        run: |
          git init
          git config user.name "GitHub Actions Bot"
          git config user.email "copperion@outlook.com"
          git add --all .
          git commit -m "Deploy from GitHub: $GITHUB_SHA"
          git push --force --quiet "https://CcoRMLeNqi:${{ secrets.CODING_TOKEN }}@e.coding.net/copperion/irz_build.git" master:master


      
