name: Yarn CI

on: 
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run Yarn Install & Build
      working-directory: ./web
      run: |
        yarn install
        yarn run build
    - name: Deploy to GitHub branch
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: website # The branch the action should deploy to.
        FOLDER: web/dist # The folder the action should deploy.
